# Generated by Django 4.0.4 on 2022-04-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255, verbose_name='Date')),
                ('Title', models.CharField(max_length=255, verbose_name='Title')),
                ('Аmount', models.CharField(max_length=255, verbose_name='Аmount')),
                ('Distance', models.CharField(max_length=255, verbose_name='Distance')),
            ],
        ),
    ]
