# Generated by Django 4.0.4 on 2022-04-14 18:28

from django.db import migrations

def create_data(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    Customer(Date="Customer 001", Title="Customer 001", Аmount="Customer 001", Distance="Customer 001").save()

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
